import { Box } from '@mui/material';
import SearchBar from '@/components/SearchBar';
import { useEffect, useState } from 'react';
import { BaseImage } from '@/type';
import ImageItem from '@/components/ImageItem';

const defaultImageList = [
  { name: '需不需要我把她叫醒' },
  { name: '就讓我們開始吧' },
  { name: '多麼可笑啊' },
  { name: '乞求吧' },
  { name: '我們先走了' },
  { name: '記得要強調是史上最快喔' },
  { name: '祝夜晚愉快' },
  { name: '難保不會有誰在偷看' },
  { name: '妳怕會有人爆料嗎' },
  { name: '昨天還很喜歡，今天就膩了' },
  { name: '世間可是很殘酷的' },
  { name: '請把妳剩餘的人生交給我' },
  { name: '這是當然的' },
  { name: '我認為沒有人比妳更適合了' },
  { name: '妳一定是會被慫恿買水晶的那種人吧' },
  { name: '好過分喔' },
  { name: '這一點也不算是負擔喔' },
  { name: '現在終於實現了' },
  { name: '我看我還是消失比較好' },
  { name: '別說這種莫名其妙的話' },
  { name: '好了，振作一點' },
  { name: '該走了' },
  { name: '真是太好了' },
  { name: '不可以' },
  { name: '他造成了168億的損失' },
  { name: '怎麼會' },
  { name: '只能說妳運氣不好' },
  { name: '忘了妳父親，成為我的女兒吧' },
  { name: '妳這種溫室長大的孩子打算怎麼在外討生活' },
  { name: '就是這裡嗎' },
  { name: '收入實在太少了' },
  { name: '妳真的要離開了嗎' },
  { name: '拿到門票了，真是奇蹟' },
  { name: '我還以為沒希望了呢' },
  { name: '趁現在先習慣一下比較好啦' },
  { name: '走開' },
  { name: '妳講話很大聲耶' },
  { name: '我沒興趣' },
  { name: '所以呢' },
  { name: '剩這一張該怎麼辦呢' },
  { name: '幹嘛' },
  { name: '我要出門了' },
  { name: '我已經沒辦法再努力了' },
  { name: '自己好沒用' },
  { name: '他根本不懂我這些日子有多難熬' },
  { name: '當然不會有問題' },
  { name: '妳以為我是為了什麼才努力過來的' },
  { name: '斬斷過去的留戀' },
  { name: '忘記所有的一切' },
  { name: '真是無趣的劇本' },
  { name: '那種虛假的笑容' },
  { name: '才沒有人想要呢' },
  { name: '應該發自內心去笑才對啊' },
  { name: '妳怎麼做出這種事' },
  { name: '看妳做了什麼好事' },
  { name: '這發展已經無法停止了' },
  { name: '真是的' },
  { name: '掛斷了' },
  { name: '為什麼做出那種膚淺的行為' },
  { name: '不是獲得空前成功嗎' },
  { name: '妳看，通知一直響個不停喔' },
  { name: '不選今天要選什麼時候' },
  { name: '妳這麼快就要走了啊' },
  { name: '我的話還沒有說完' },
  { name: '根本就沒有理由反對吧' },
  { name: '我的意思就是速度太快了' },
  { name: '早安' },
  { name: '有找到不錯的石頭嗎' },
  { name: '我都不知道耶' },
  { name: '對不起瞞著妳' },
  { name: '對不起一直瞞著大家' },
  { name: '因為有保密義務' },
  { name: '她放學後就不知道跑到哪去了' },
  { name: '妳是唯一找到我的人' },
  { name: '那種事交給擅長應對的人來就好了' },
  { name: '之前明明就不肯和我組樂團' },
  { name: '哪可能不被她知道啊' },
  { name: '我完全沒發現是她呢' },
  { name: '這又沒什麼好說的' },
  { name: '就在一旁起鬨' },
  { name: '好氣喔' },
  { name: '因為我的臉蛋也很漂亮' },
  { name: '是沒錯啦' },
  { name: '這樣會被人看扁的喔' },
  { name: '害我都忍不住懷疑妳了' },
  { name: '這種狀況不會持續太久' },
  { name: '我一直想挑戰各式各樣的事物' },
  { name: '因為再也沒有這種機會了嘛' },
  { name: '之前拋棄了我，現在還有臉回來' },
  { name: '我一點也不想看到你' },
  { name: '超催淚的' },
  { name: '太精采了' },
  { name: '妳能理解我真高興' },
  { name: '真的可以嗎' },
  { name: '妳很不好溝通耶' },
  { name: '不會持續太久的' },
  { name: '簡直糟透了' },
  { name: '為什麼還搞成那樣' },
  { name: '今後發言時請保有自己是專業人士的自覺' },
  { name: '抱歉' },
  { name: '真是永遠不缺話題呢' },
  { name: '不會啊' },
  { name: '真的動不動就有人在傳要解散或感情不和呢' },
  { name: '害我差點忍不住大喊Sumimi才不會解散了呢' },
  { name: '我沒事' },
  { name: '謝謝妳' },
  { name: '還是來我家過夜吧' },
  { name: '不需要跟我客氣，好嗎' },
  { name: '可以等我十秒嗎' },
  { name: '1,2...' },
  { name: '我才數到3喔' },
  { name: '妳可以一直待在這裡' },
  { name: '我會一直陪著妳' },
  { name: '這終究只是故事的劇情內容' },
  { name: '可說是殘酷的現實' },
  { name: '沒時間了，直接開始吧' },
  { name: '絕對不能失敗' },
  { name: '這就是妳所期望的' },
  { name: '很遺憾' },
  { name: '已經...逃不掉了' },
  { name: '就將一切委身於Ave Mujica吧' },
  { name: '斷了線的人偶' },
  { name: '祝妳有個好夢' },
  { name: '妳竟然能展現出那麼精采的演技' },
  { name: '那種完成度實在不像是即興演出' },
  { name: '妳也沒有試圖掩飾錯誤就那麼僵住了嗎' },
  { name: '一個也沒有' },
  { name: '妳又睡不著了嗎' },
  { name: '我辦不到' },
  { name: '我不會唱歌' },
  { name: '不是...我不是這個意思' },
  { name: '是因為我不夠好' },
  { name: '幸好總算化險為夷了' },
  { name: '我還有事得處理' },
  { name: '妳要去工作了嗎' },
  { name: '好耶' },
  { name: '我想也是' },
  { name: '這也算是種才能' },
  { name: '能用的東西本來就該多加利用' },
  { name: '未免也太扯了吧' },
  { name: '我沒在用' },
  { name: '不要怕成這樣嘛' },
  { name: '因為好像快壞掉了' },
  { name: '妳覺得自己繼續這樣好嗎' },
  { name: '再這樣下去妳們會一起完蛋的' },
  { name: '妳全都聽見了吧' },
  { name: '對健康不好喔' },
  { name: '覺得難受的話要說喔' },
  { name: '妳有在聽嗎' },
  { name: '妳沒有看郵件嗎' },
  { name: '這種事根本就不用考慮' },
  { name: '我會拒絕對方的要求' },
  { name: '應該問問本人的意見吧' },
  { name: '想也知道當然有吧' },
  { name: '不是只顧著做自己想做的事情' },
  { name: '妳到底想說什麼' },
  { name: '妳真的覺得這樣子好嗎' },
  { name: '我就是這麼覺得' },
  { name: '到底要我說幾次妳才懂' },
  { name: '為什麼變這樣了' },
  { name: '妳不要跑進來插嘴' },
  { name: '我就是無法接受' },
  { name: '大家靜下來慢慢談嘛' },
  { name: '妳還要跟著我走多久' },
  { name: '為什麼不開口說妳不願意' },
  { name: '別再撒嬌了' },
  { name: '現在說這種話的時候嗎' },
  { name: '為什麼妳不肯站在我這邊' },
  { name: '我除了這世界已經一無所有了' },
  { name: '妳一定很痛苦吧' },
  { name: '到底是怎麼回事' },
  { name: '已經不會有事了' },
  { name: '晚安，祝妳有個好夢' },
];

export default function HomePage() {
  const [imageList, setImageList] = useState<BaseImage[]>(defaultImageList);

  const searchHandler = (keyword: string) => {
    const filteredImageList = defaultImageList.filter((item) => item.name.includes(keyword));
    setImageList(filteredImageList);
  };

  useEffect(() => {
    setImageList(defaultImageList);
  }, []);
  return (
    <>
      <Box>
        <SearchBar onSearch={searchHandler} />
      </Box>
      <Box sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center' }}>
        {imageList.length === 0 && <Box sx={{ mt: 2, color: '#e6e6e6' }}>查無截圖 QQ</Box>}
        {imageList.map((image) => (
          <ImageItem key={image.name} image={image} />
        ))}
      </Box>
    </>
  );
}
