import { RootState } from '@/store/store';
import { createSelector, createSlice } from '@reduxjs/toolkit';

export const contentLayoutSlice = createSlice({
  name: 'contentLayout',
  initialState: {
    isNotificationOpen: false,
    notification: { severity: 'success', message: '' },
    keyword: '',
    episode: 0,
    defaultImageList: [
      { name: '需不需要我把她叫醒', episode: 1 },
      { name: '就讓我們開始吧', episode: 1 },
      { name: '多麼可笑啊', episode: 1 },
      { name: '乞求吧', episode: 1 },
      { name: '我們先走了', episode: 1 },
      { name: '記得要強調是史上最快喔', episode: 1 },
      { name: '祝夜晚愉快', episode: 1 },
      { name: '難保不會有誰在偷看', episode: 1 },
      { name: '妳怕會有人爆料嗎', episode: 1 },
      { name: '昨天還很喜歡，今天就膩了', episode: 1 },
      { name: '世間可是很殘酷的', episode: 1 },
      { name: '請把妳剩餘的人生交給我', episode: 1 },
      { name: '這是當然的', episode: 1 },
      { name: '我認為沒有人比妳更適合了', episode: 1 },
      { name: '妳一定是會被慫恿買水晶的那種人吧', episode: 1 },
      { name: '好過分喔', episode: 1 },
      { name: '這一點也不算是負擔喔', episode: 1 },
      { name: '現在終於實現了', episode: 1 },
      { name: '我看我還是消失比較好', episode: 1 },
      { name: '別說這種莫名其妙的話', episode: 1 },
      { name: '好了，振作一點', episode: 1 },
      { name: '該走了', episode: 1 },
      { name: '真是太好了', episode: 1 },
      { name: '不可以', episode: 1 },
      { name: '他造成了168億的損失', episode: 1 },
      { name: '怎麼會', episode: 1 },
      { name: '只能說妳運氣不好', episode: 1 },
      { name: '忘了妳父親，成為我的女兒吧', episode: 1 },
      { name: '妳這種溫室長大的孩子打算怎麼在外討生活', episode: 1 },
      { name: '就是這裡嗎', episode: 1 },
      { name: '收入實在太少了', episode: 1 },
      { name: '妳真的要離開了嗎', episode: 1 },
      { name: '拿到門票了，真是奇蹟', episode: 1 },
      { name: '我還以為沒希望了呢', episode: 1 },
      { name: '趁現在先習慣一下比較好啦', episode: 1 },
      { name: '走開', episode: 1 },
      { name: '妳講話很大聲耶', episode: 1 },
      { name: '我沒興趣', episode: 1 },
      { name: '所以呢', episode: 1 },
      { name: '剩這一張該怎麼辦呢', episode: 1 },
      { name: '幹嘛', episode: 1 },
      { name: '我要出門了', episode: 1 },
      { name: '我已經沒辦法再努力了', episode: 1 },
      { name: '自己好沒用', episode: 1 },
      { name: '他根本不懂我這些日子有多難熬', episode: 1 },
      { name: '當然不會有問題', episode: 1 },
      { name: '妳以為我是為了什麼才努力過來的', episode: 1 },
      { name: '斬斷過去的留戀', episode: 1 },
      { name: '忘記所有的一切', episode: 1 },
      { name: '我現在只剩下Ave Mujica了', episode: 1 },
      { name: '真是無趣的劇本', episode: 1 },
      { name: '那種虛假的笑容', episode: 1 },
      { name: '才沒有人想要呢', episode: 1 },
      { name: '應該發自內心去笑才對啊', episode: 1 },
      { name: '妳怎麼做出這種事', episode: 1 },
      { name: '看妳做了什麼好事', episode: 1 },
      { name: '這發展已經無法停止了', episode: 1 },

      { name: '真是的', episode: 2 },
      { name: '掛斷了', episode: 2 },
      { name: '為什麼做出那種膚淺的行為', episode: 2 },
      { name: '不是獲得空前成功嗎', episode: 2 },
      { name: '妳看，通知一直響個不停喔', episode: 2 },
      { name: '不選今天要選什麼時候', episode: 2 },
      { name: '妳這麼快就要走了啊', episode: 2 },
      { name: '我的話還沒有說完', episode: 2 },
      { name: '根本就沒有理由反對吧', episode: 2 },
      { name: '我的意思就是速度太快了', episode: 2 },
      { name: '早安', episode: 2 },
      { name: '有找到不錯的石頭嗎', episode: 2 },
      { name: '我都不知道耶', episode: 2 },
      { name: '對不起瞞著妳', episode: 2 },
      { name: '對不起一直瞞著大家', episode: 2 },
      { name: '因為有保密義務', episode: 2 },
      { name: '她放學後就不知道跑到哪去了', episode: 2 },
      { name: '妳是唯一找到我的人', episode: 2 },
      { name: '那種事交給擅長應對的人來就好了', episode: 2 },
      { name: '之前明明就不肯和我組樂團', episode: 2 },
      { name: '哪可能不被她知道啊', episode: 2 },
      { name: '我完全沒發現是她呢', episode: 2 },
      { name: '這又沒什麼好說的', episode: 2 },
      { name: '就在一旁起鬨', episode: 2 },
      { name: '好氣喔', episode: 2 },
      { name: '因為我的臉蛋也很漂亮', episode: 2 },
      { name: '是沒錯啦', episode: 2 },
      { name: '這樣會被人看扁的喔', episode: 2 },
      { name: '害我都忍不住懷疑妳了', episode: 2 },
      { name: '這種狀況不會持續太久', episode: 2 },
      { name: '我一直想挑戰各式各樣的事物', episode: 2 },
      { name: '因為再也沒有這種機會了嘛', episode: 2 },
      { name: '之前拋棄了我，現在還有臉回來', episode: 2 },
      { name: '我一點也不想看到你', episode: 2 },
      { name: '超催淚的', episode: 2 },
      { name: '太精采了', episode: 2 },
      { name: '妳能理解我真高興', episode: 2 },
      { name: '真的可以嗎', episode: 2 },
      { name: '妳很不好溝通耶', episode: 2 },
      { name: '不會持續太久的', episode: 2 },
      { name: '簡直糟透了', episode: 2 },
      { name: '為什麼還搞成那樣', episode: 2 },
      { name: '今後發言時請保有自己是專業人士的自覺', episode: 2 },
      { name: '抱歉', episode: 2 },
      { name: '真是永遠不缺話題呢', episode: 2 },
      { name: '不會啊', episode: 2 },
      { name: '真的動不動就有人在傳要解散或感情不和呢', episode: 2 },
      { name: '害我差點忍不住大喊Sumimi才不會解散了呢', episode: 2 },
      { name: '我沒事', episode: 2 },
      { name: '謝謝妳', episode: 2 },
      { name: '還是來我家過夜吧', episode: 2 },
      { name: '不需要跟我客氣，好嗎', episode: 2 },
      { name: '可以等我十秒嗎', episode: 2 },
      { name: '1,2...', episode: 2 },
      { name: '我才數到3喔', episode: 2 },
      { name: '妳可以一直待在這裡', episode: 2 },
      { name: '我會一直陪著妳', episode: 2 },
      { name: '這終究只是故事的劇情內容', episode: 2 },
      { name: '可說是殘酷的現實', episode: 2 },
      { name: '沒時間了，直接開始吧', episode: 2 },
      { name: '絕對不能失敗', episode: 2 },
      { name: '這就是妳所期望的', episode: 2 },
      { name: '很遺憾', episode: 2 },
      { name: '已經...逃不掉了', episode: 2 },
      { name: '就將一切委身於Ave Mujica吧', episode: 2 },
      { name: '斷了線的人偶', episode: 2 },

      { name: '祝妳有個好夢', episode: 3 },
      { name: '妳竟然能展現出那麼精采的演技', episode: 3 },
      { name: '那種完成度實在不像是即興演出', episode: 3 },
      { name: '妳也沒有試圖掩飾錯誤就那麼僵住了嗎', episode: 3 },
      { name: '一個也沒有', episode: 3 },
      { name: '妳又睡不著了嗎', episode: 3 },
      { name: '我辦不到', episode: 3 },
      { name: '我不會唱歌', episode: 3 },
      { name: '不是...我不是這個意思', episode: 3 },
      { name: '是因為我不夠好', episode: 3 },
      { name: '幸好總算化險為夷了', episode: 3 },
      { name: '我還有事得處理', episode: 3 },
      { name: '妳要去工作了嗎', episode: 3 },
      { name: '好耶', episode: 3 },
      { name: '我想也是', episode: 3 },
      { name: '這也算是種才能', episode: 3 },
      { name: '能用的東西本來就該多加利用', episode: 3 },
      { name: '未免也太扯了吧', episode: 3 },
      { name: '我沒在用', episode: 3 },
      { name: '不要怕成這樣嘛', episode: 3 },
      { name: '因為好像快壞掉了', episode: 3 },
      { name: '妳覺得自己繼續這樣好嗎', episode: 3 },
      { name: '再這樣下去妳們會一起完蛋的', episode: 3 },
      { name: '妳全都聽見了吧', episode: 3 },
      { name: '對健康不好喔', episode: 3 },
      { name: '覺得難受的話要說喔', episode: 3 },
      { name: '妳有在聽嗎', episode: 3 },
      { name: '妳沒有看郵件嗎', episode: 3 },
      { name: '這種事根本就不用考慮', episode: 3 },
      { name: '我會拒絕對方的要求', episode: 3 },
      { name: '應該問問本人的意見吧', episode: 3 },
      { name: '想也知道當然有吧', episode: 3 },
      { name: '不是只顧著做自己想做的事情', episode: 3 },
      { name: '妳到底想說什麼', episode: 3 },
      { name: '妳真的覺得這樣子好嗎', episode: 3 },
      { name: '我就是這麼覺得', episode: 3 },
      { name: '到底要我說幾次妳才懂', episode: 3 },
      { name: '為什麼變這樣了', episode: 3 },
      { name: '妳不要跑進來插嘴', episode: 3 },
      { name: '我就是無法接受', episode: 3 },
      { name: '大家靜下來慢慢談嘛', episode: 3 },
      { name: '妳還要跟著我走多久', episode: 3 },
      { name: '為什麼不開口說妳不願意', episode: 3 },
      { name: '別再撒嬌了', episode: 3 },
      { name: '現在說這種話的時候嗎', episode: 3 },
      { name: '為什麼妳不肯站在我這邊', episode: 3 },
      { name: '我除了這世界已經一無所有了', episode: 3 },
      { name: '妳一定很痛苦吧', episode: 3 },
      { name: '到底是怎麼回事', episode: 3 },
      { name: '已經不會有事了', episode: 3 },
      { name: '晚安，祝妳有個好夢', episode: 3 },

      { name: '因為我不知道Mujica的歌啊', episode: 4 },
      { name: '不可能有這種事吧', episode: 4 },
      { name: '到底是怎麼樣啊', episode: 4 },
      { name: '謝謝大家', episode: 4 },
      { name: '世界開始變得扭曲不堪', episode: 4 },
      { name: '好猶豫喔', episode: 4 },
      { name: '不對，我現在正在減肥', episode: 4 },
      { name: '我不管怎麼吃都不會胖', episode: 4 },
      { name: '分一半給別人的話，熱量也會減半喔', episode: 4 },
      { name: '不對不對，話不能這樣講啦', episode: 4 },
      { name: '又有什麼關係嘛', episode: 4 },
      { name: '我會寫出配得上Ave Mujica的歌曲', episode: 4 },
      { name: '所謂的命運共同體不就是這樣嗎', episode: 4 },
      { name: '太誇張了啦', episode: 4 },
      { name: '妳們想隨便帶過這話題嗎', episode: 4 },
      { name: '我的話還沒有說完_2', episode: 4 },
      { name: '我也很想快點練習啊', episode: 4 },
      { name: '我也一起幫忙吧', episode: 4 },
      { name: '昨天也一整夜都沒睡', episode: 4 },
      { name: '對健康不好喔_2', episode: 4 },
      { name: '跟她這樣說，叫她好好睡覺', episode: 4 },
      { name: '各方面都會變得不正常喔', episode: 4 },
      { name: '和妳在一起很自在', episode: 4 },
      { name: '都不曉得妳有這樣的一面', episode: 4 },
      { name: '我的想法也和妳一樣', episode: 4 },
      { name: '因為現在最貼近祥子的人就是妳了', episode: 4 },
      { name: '祥子今後就拜託妳了', episode: 4 },
      { name: '剛才的那些話要和祥子保密喔', episode: 4 },
      { name: '對健康不好喔_3', episode: 4 },
      { name: '這樣會睡眠不足的', episode: 4 },
      { name: '[無詞]海玲拍攝利希筆記', episode: 4 },
      { name: '沒睡飽嗎', episode: 4 },
      { name: '那是我擅長的課目，不必了', episode: 4 },
      { name: '要借數學嗎', episode: 4 },
      { name: '因為教室實在太吵了', episode: 4 },
      { name: '那件事已經解決了', episode: 4 },
      { name: '就像即將燃盡前的線香煙火呢', episode: 4 },
      { name: '[無詞]睦用手幫小祥推笑臉', episode: 4 },
      { name: '沒錯沒錯，放開一點嘛', episode: 4 },
      { name: '[無詞]Ave Mujica團體五人合照', episode: 4 },
      { name: '我也很喜歡這張照片', episode: 4 },
      { name: '那就決定選這張了', episode: 4 },
      { name: '我很期待能去那裡看看', episode: 4 },
      { name: '希望大家也在Mujica的社群帳號留下其他推薦景點和留言喔', episode: 4 },
      { name: '謝謝妳的邀請', episode: 4 },
      { name: '這樣誰受得了啊', episode: 4 },
      { name: '拋話題給她接還直接無視掉，氣死了', episode: 4 },
      { name: '再怎麼努力也就只有這樣', episode: 4 },
      { name: '果然還是比不過才能嘛', episode: 4 },
      { name: '麥子就是越被踩踏長得越堅強啊', episode: 4 },
      { name: '[無詞]祐天寺若麥哭哭臉', episode: 4 },
      { name: '生日快樂', episode: 4 },
      { name: '大家都會為妳加油的', episode: 4 },
      { name: '謝謝大家，我會加油的', episode: 4 },
      { name: '因為我不會彈吉他啊', episode: 4 },
      { name: '我全都不會彈喔', episode: 4 },
      { name: '我真的完全聽不懂', episode: 4 },
      { name: '妳現在是認真的嗎', episode: 4 },
      { name: '有哪裡不行', episode: 4 },
      { name: '我真的已經搞不懂妳了', episode: 4 },
      { name: '這全是為了Ave Mujica', episode: 4 },
      { name: '妳真的不懂嗎', episode: 4 },
      { name: '我是認真的', episode: 4 },
      { name: '所以我討厭妳', episode: 4 },
      { name: '放心吧', episode: 4 },
      { name: '[無詞]Mortis側看祥子', episode: 4 },
      { name: '叫我嗎', episode: 4 },
      { name: '[無詞]Mortis俯身看低頭的祥子', episode: 4 },
      { name: '妳真的有雙重人格嗎', episode: 4 },
      { name: '我也已經忍耐很久了', episode: 4 },
      { name: '妳打算辜負他們嗎', episode: 4 },
      { name: '不然妳乾脆退出算了', episode: 4 },
      { name: '簡直蠢斃了', episode: 4 },
      { name: '我不幹了', episode: 4 },
      { name: '為什麼話題會變成這樣', episode: 4 },
      { name: '妳冷靜一點', episode: 4 },
      { name: '我很冷靜', episode: 4 },
      { name: '初華就只會騙人', episode: 4 },
      { name: '不要不要', episode: 4 },
      { name: '這種事早晚會發生的', episode: 4 },
      { name: '反了吧', episode: 4 },
      { name: '什麼意思', episode: 4 },
      { name: '我真的被妳震撼到了', episode: 4 },
      { name: '妳不該待在這裡', episode: 4 },
      { name: '為什麼 為什麼要說這種壞心眼的話', episode: 4 },
      { name: '怎麼會...', episode: 4 },
      { name: '沉默隨即宣告了一切的終焉', episode: 4 },
      { name: '不要...不要說', episode: 4 },
      { name: '不要', episode: 4 },

      { name: '請好好向我說明事情的經過', episode: 5 },
      { name: '恐怕會花一些時間，還請多多包涵', episode: 5 },
      { name: '打擾了', episode: 5 },
      { name: '請問可以占用一些時間嗎', episode: 5 },
      { name: '我有點事想和您談談', episode: 5 },
      { name: '好可憐喔', episode: 5 },
      { name: '妳不需要接電話', episode: 5 },
      { name: '妳可以一直留在這裡', episode: 5 },
      { name: '你也願意陪在我身邊嗎', episode: 5 },
      { name: '能否占用妳一些時間呢', episode: 5 },
      { name: '你們覺得如果是找我我就會願意回答嗎', episode: 5 },
      { name: '她現在是Sumimi的小初喔', episode: 5 },
      { name: '[無詞]客服小祥', episode: 5 },
      { name: '[無詞]退勤', episode: 5 },
      { name: '對不起，都怪我這麼沒用', episode: 5 },
      { name: '對不起，祥子', episode: 5 },
      { name: '那個很有參考價值喔', episode: 5 },
      { name: '謝謝誇獎', episode: 5 },
      { name: '妳真的很奮發向上呢', episode: 5 },
      { name: '我只是想挑戰所有自己能做的事情而已', episode: 5 },
      { name: '妳為什麼有辦法這麼努力呢', episode: 5 },
      { name: '為了這目標，我什麼都有辦法做', episode: 5 },
      { name: '說穿了也只是群大小姐在玩樂團遊戲吧', episode: 5 },
      { name: '真受不了', episode: 5 },
      { name: '都已經過一個月了', episode: 5 },
      { name: '(我想要多了解小祥)', episode: 5 },
      { name: '妳何不自己去確認呢', episode: 5 },
      { name: '這次的事讓妳上到一課了吧', episode: 5 },
      { name: '我都已經替妳付清了', episode: 5 },
      { name: '我等妳三分鐘', episode: 5 },
      { name: '[無詞]祥爸望向窗外', episode: 5 },
      { name: '意外地是個倔強野丫頭', episode: 5 },
      { name: '你可要好好看住她', episode: 5 },
      { name: '好討厭我自己', episode: 5 },
      { name: '我現在想朝綜藝方面努力發展', episode: 5 },
      { name: '[無詞]喵夢生氣咬牙表情', episode: 5 },
      { name: '原來她真的是個大小姐耶', episode: 5 },
      { name: '豐~川~集~團~_T', episode: 5 },
      { name: '豐~川~集~團~_G', episode: 5 },
      { name: '豐~川~集~團~_W', episode: 5 },
      { name: '豐~川~集~團~_V', episode: 5 },
      { name: '幸福到底是什麼呢', episode: 5 },
      { name: '[無詞]立希吃驚表情', episode: 5 },
      { name: '我...我現在就很幸福了啊', episode: 5 },
      { name: '沒什麼', episode: 5 },
      { name: '再見', episode: 5 },
      { name: '我都差點忍不住想和樂團名一樣大喊聽聽我們的歌吧', episode: 5 },
      { name: '妳又在貼了嗎', episode: 5 },
      { name: '她有給妳答覆嗎', episode: 5 },
      { name: '(小祥，妳幸福嗎)', episode: 5 },
      { name: '(已經夠了)', episode: 5 },
      { name: '怎麼了', episode: 5 },
      { name: '交給我吧', episode: 5 },
      { name: '我國中三年間都是班上的最後一棒跑者', episode: 5 },
      { name: '我是她朋友', episode: 5 },
      { name: '[無詞]愛音張嘴嘆氣', episode: 5 },
      { name: '不過這輛車真的好豪華喔', episode: 5 },
      { name: '椅子坐起來超貼合身體的', episode: 5 },
      { name: '也太大了吧', episode: 5 },
      { name: '來組樂團吧', episode: 5 },
      { name: '是的...是的...', episode: 5 },
      { name: '不，她一直不省人事', episode: 5 },
      { name: '喂喂 請問是醫生嗎', episode: 5 },
      { name: '[無詞]爽世看Mortis時驚恐表情_1', episode: 5 },
      { name: '她一直在沉睡著', episode: 5 },
      { name: '[無詞]爽世看Mortis時驚恐表情_2', episode: 5 },
      { name: '[無詞]爽世看Mortis時驚恐表情_3', episode: 5 },
      { name: '拜託妳...', episode: 5 },
    ],
  },
  reducers: {
    setNotificationOpen: (state, action) => {
      state.isNotificationOpen = action.payload;
    },
    setNotification: (state, action) => {
      state.notification = action.payload;
    },
    setKeyword: (state, action) => {
      state.keyword = action.payload;
    },
    setEpisode: (state, action) => {
      state.episode = action.payload;
    },
  },
});

export const latestEpisodeSelector = createSelector(
  (state: RootState) => state.contentLayout.defaultImageList,
  (defaultImageList) => defaultImageList[defaultImageList.length - 1].episode
);

export const { setNotificationOpen, setNotification, setKeyword, setEpisode } = contentLayoutSlice.actions;

export default contentLayoutSlice.reducer;
